// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqtDLfXugVtAwD29dZIs0DvrtYvZVgu7c',
    appId: '1:984453639345:web:c46e4c8043dfd0d3684690',
    messagingSenderId: '984453639345',
    projectId: 'fitnessapp-357b0',
    authDomain: 'fitnessapp-357b0.firebaseapp.com',
    storageBucket: 'fitnessapp-357b0.firebasestorage.app',
    measurementId: 'G-KKWBGB2HJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOcaZ1Cd8Uxv2SoKvmRSYBvYT2M3OaeoI',
    appId: '1:984453639345:android:5a1613e93238b6cf684690',
    messagingSenderId: '984453639345',
    projectId: 'fitnessapp-357b0',
    storageBucket: 'fitnessapp-357b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARATxWcP-C0NXGFDbnTq3qU1RHkck2wSI',
    appId: '1:984453639345:ios:9d670f42374c9252684690',
    messagingSenderId: '984453639345',
    projectId: 'fitnessapp-357b0',
    storageBucket: 'fitnessapp-357b0.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARATxWcP-C0NXGFDbnTq3qU1RHkck2wSI',
    appId: '1:984453639345:ios:9d670f42374c9252684690',
    messagingSenderId: '984453639345',
    projectId: 'fitnessapp-357b0',
    storageBucket: 'fitnessapp-357b0.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqtDLfXugVtAwD29dZIs0DvrtYvZVgu7c',
    appId: '1:984453639345:web:4f1ab3c4ff24e7b5684690',
    messagingSenderId: '984453639345',
    projectId: 'fitnessapp-357b0',
    authDomain: 'fitnessapp-357b0.firebaseapp.com',
    storageBucket: 'fitnessapp-357b0.firebasestorage.app',
    measurementId: 'G-21QQSW700F',
  );
}
